// Package config loads and validates process configuration from the environment.
//
// Every value the server needs is resolved once at startup. Anything missing or
// malformed is reported as a single combined error so an operator fixes their
// whole .env in one pass instead of restarting once per typo.
package config

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

// EncryptionKeySize is the required decoded length of APP_ENCRYPTION_KEY.
// AES-256-GCM takes a 32 byte key; nothing shorter is accepted.
const EncryptionKeySize = 32

type DatabaseDriver string

const (
	DriverPostgres DatabaseDriver = "postgres"
	DriverSQLite   DatabaseDriver = "sqlite"
)

type Config struct {
	Env    string // "development" or "production"
	Port   int
	AppURL string

	DatabaseDriver DatabaseDriver
	DatabaseURL    string

	// EncryptionKey seals credentials at rest. Losing it makes every stored
	// SSH key, registry password and deployment secret unrecoverable.
	EncryptionKey []byte
	SessionSecret []byte

	// SecretsPath is the file where keys were loaded/saved if auto-generated.
	SecretsPath          string
	AutoGeneratedSecrets bool

	LogLevel      slog.Level
	ShutdownGrace time.Duration

	// Deployments publish on a loopback port from this range, so two
	// applications on one server cannot collide and nothing is exposed
	// publicly until nginx is put in front of it.
	DeployPortMin int
	DeployPortMax int
	// DeployRemoteRoot is where checkouts live, relative to the SSH user home.
	DeployRemoteRoot string
	// DeployConcurrency bounds how many builds run at once.
	DeployConcurrency int
}

func (c *Config) IsProduction() bool { return c.Env == "production" }

// Load reads configuration from the environment.
func Load() (*Config, error) {
	var problems []string
	note := func(format string, args ...any) {
		problems = append(problems, fmt.Sprintf(format, args...))
	}

	cfg := &Config{
		Env:           envOr("APP_ENV", "development"),
		AppURL:        strings.TrimRight(envOr("APP_URL", "http://localhost:8081"), "/"),
		ShutdownGrace: 30 * time.Second,

		DeployRemoteRoot:  envOr("DEPLOY_REMOTE_ROOT", ".dockdeploy/apps"),
		DeployConcurrency: 2,
	}

	rawDB := strings.TrimSpace(os.Getenv("DATABASE_URL"))
	if rawDB == "" {
		rawDB = strings.TrimSpace(os.Getenv("SQLITE_PATH"))
	}
	driverEnv := strings.ToLower(strings.TrimSpace(os.Getenv("DATABASE_DRIVER")))

	if driverEnv == "postgres" || strings.HasPrefix(rawDB, "postgres://") || strings.HasPrefix(rawDB, "postgresql://") {
		cfg.DatabaseDriver = DriverPostgres
		cfg.DatabaseURL = rawDB
		if cfg.DatabaseURL == "" {
			note("DATABASE_URL is required when using postgres (e.g. postgres://user:pass@host:5432/dockdeploy?sslmode=disable)")
		}
	} else {
		// SQLite is used when Postgres is not set, or when SQLite is explicitly specified
		cfg.DatabaseDriver = DriverSQLite
		if rawDB == "" {
			cfg.DatabaseURL = "dockdeploy.db"
		} else {
			trimmed := strings.TrimPrefix(rawDB, "sqlite://")
			trimmed = strings.TrimPrefix(trimmed, "sqlite:")
			cfg.DatabaseURL = trimmed
		}
	}

	var err error

	cfg.DeployPortMin, err = envInt("DEPLOY_PORT_MIN", 20000)
	if err != nil {
		note("%v", err)
	}
	cfg.DeployPortMax, err = envInt("DEPLOY_PORT_MAX", 29999)
	if err != nil {
		note("%v", err)
	}
	if cfg.DeployPortMin >= cfg.DeployPortMax {
		note("DEPLOY_PORT_MIN (%d) must be below DEPLOY_PORT_MAX (%d)", cfg.DeployPortMin, cfg.DeployPortMax)
	}

	cfg.DeployConcurrency, err = envInt("DEPLOY_CONCURRENCY", 2)
	if err != nil {
		note("%v", err)
	} else if cfg.DeployConcurrency < 1 || cfg.DeployConcurrency > 16 {
		note("DEPLOY_CONCURRENCY must be between 1 and 16")
	}

	if cfg.Env != "development" && cfg.Env != "production" {
		note("APP_ENV must be 'development' or 'production', got %q", cfg.Env)
	}

	port, err := strconv.Atoi(envOr("PORT", "8081"))
	if err != nil || port < 1 || port > 65535 {
		note("PORT must be a number between 1 and 65535, got %q", os.Getenv("PORT"))
	}
	cfg.Port = port

	if err := resolveSecrets(cfg); err != nil {
		note("%v", err)
	}

	switch level := strings.ToLower(envOr("LOG_LEVEL", "info")); level {
	case "debug":
		cfg.LogLevel = slog.LevelDebug
	case "info":
		cfg.LogLevel = slog.LevelInfo
	case "warn":
		cfg.LogLevel = slog.LevelWarn
	case "error":
		cfg.LogLevel = slog.LevelError
	default:
		note("LOG_LEVEL must be one of debug|info|warn|error, got %q", level)
	}

	if len(problems) > 0 {
		return nil, fmt.Errorf("invalid configuration:\n  - %s", strings.Join(problems, "\n  - "))
	}
	return cfg, nil
}

// resolveSecrets resolves EncryptionKey and SessionSecret.
// If provided in the environment, it uses them.
// If not provided in the environment (e.g. running locally with zero dependencies):
// It loads from or securely generates a persistent .key file next to the SQLite database.
func resolveSecrets(cfg *Config) error {
	var encKeyErr, sessSecretErr error
	cfg.EncryptionKey, encKeyErr = decodeKey("APP_ENCRYPTION_KEY", EncryptionKeySize)
	cfg.SessionSecret, sessSecretErr = decodeKey("SESSION_SECRET", 32)

	if encKeyErr == nil && sessSecretErr == nil {
		return nil
	}

	// For SQLite / local zero-dependency mode, auto-provision persistent secrets if missing from env
	keyPath := os.Getenv("SECRETS_FILE")
	if keyPath == "" {
		if cfg.DatabaseDriver == DriverSQLite {
			dbPath := cfg.DatabaseURL
			if idx := strings.Index(dbPath, "?"); idx >= 0 {
				dbPath = dbPath[:idx]
			}
			keyPath = dbPath + ".key"
		} else {
			keyPath = ".dockdeploy.key"
		}
	}

	// Try reading existing key file
	if data, err := os.ReadFile(keyPath); err == nil {
		lines := strings.Split(string(data), "\n")
		var rawEnc, rawSess string
		for _, line := range lines {
			line = strings.TrimSpace(line)
			if strings.HasPrefix(line, "#") || line == "" {
				continue
			}
			if strings.HasPrefix(line, "APP_ENCRYPTION_KEY=") {
				rawEnc = strings.TrimPrefix(line, "APP_ENCRYPTION_KEY=")
			} else if strings.HasPrefix(line, "SESSION_SECRET=") {
				rawSess = strings.TrimPrefix(line, "SESSION_SECRET=")
			}
		}

		if cfg.EncryptionKey == nil && rawEnc != "" {
			if k, err := base64.StdEncoding.DecodeString(strings.TrimSpace(rawEnc)); err == nil && len(k) == EncryptionKeySize {
				cfg.EncryptionKey = k
			}
		}
		if cfg.SessionSecret == nil && rawSess != "" {
			if k, err := base64.StdEncoding.DecodeString(strings.TrimSpace(rawSess)); err == nil && len(k) >= 32 {
				cfg.SessionSecret = k
			}
		}

		if cfg.EncryptionKey != nil && cfg.SessionSecret != nil {
			cfg.SecretsPath = keyPath
			return nil
		}
	}

	// Generate new keys if still missing
	var newEncBytes, newSessBytes []byte
	if cfg.EncryptionKey == nil {
		newEncBytes = make([]byte, EncryptionKeySize)
		if _, err := rand.Read(newEncBytes); err != nil {
			return fmt.Errorf("generate encryption key: %w", err)
		}
		cfg.EncryptionKey = newEncBytes
	} else {
		newEncBytes = cfg.EncryptionKey
	}

	if cfg.SessionSecret == nil {
		newSessBytes = make([]byte, 32)
		if _, err := rand.Read(newSessBytes); err != nil {
			return fmt.Errorf("generate session secret: %w", err)
		}
		cfg.SessionSecret = newSessBytes
	} else {
		newSessBytes = cfg.SessionSecret
	}

	encBase64 := base64.StdEncoding.EncodeToString(newEncBytes)
	sessBase64 := base64.StdEncoding.EncodeToString(newSessBytes)

	content := fmt.Sprintf(`# dockdeploy persistent local secrets
# Automatically generated on first startup for zero-dependency local mode.
# IMPORTANT: Back up this key file. Stored credentials cannot be decrypted without APP_ENCRYPTION_KEY.
APP_ENCRYPTION_KEY=%s
SESSION_SECRET=%s
`, encBase64, sessBase64)

	// Ensure parent directory exists
	if dir := filepath.Dir(keyPath); dir != "" && dir != "." {
		_ = os.MkdirAll(dir, 0755)
	}

	if err := os.WriteFile(keyPath, []byte(content), 0600); err != nil {
		if encKeyErr != nil {
			return encKeyErr
		}
		if sessSecretErr != nil {
			return sessSecretErr
		}
		return fmt.Errorf("write secrets file %s: %w", keyPath, err)
	}

	cfg.SecretsPath = keyPath
	cfg.AutoGeneratedSecrets = true
	return nil
}

// decodeKey reads a base64 encoded secret and checks its decoded length.
func decodeKey(name string, want int) ([]byte, error) {
	raw := os.Getenv(name)
	if raw == "" {
		return nil, fmt.Errorf("%s is required; generate one with: openssl rand -base64 %d", name, want)
	}
	key, err := base64.StdEncoding.DecodeString(strings.TrimSpace(raw))
	if err != nil {
		return nil, fmt.Errorf("%s must be valid standard base64: %w", name, err)
	}
	if len(key) != want {
		return nil, fmt.Errorf("%s must decode to %d bytes, got %d; generate one with: openssl rand -base64 %d", name, want, len(key), want)
	}
	return key, nil
}

// envInt reads a numeric setting, reporting a usable message rather than
// silently falling back on a typo.
func envInt(name string, fallback int) (int, error) {
	raw := os.Getenv(name)
	if raw == "" {
		return fallback, nil
	}
	value, err := strconv.Atoi(strings.TrimSpace(raw))
	if err != nil {
		return fallback, fmt.Errorf("%s must be a whole number, got %q", name, raw)
	}
	return value, nil
}

func envOr(name, fallback string) string {
	if v := os.Getenv(name); v != "" {
		return v
	}
	return fallback
}
