package config

import (
	"encoding/base64"
	"testing"
)

func validKey() string {
	return base64.StdEncoding.EncodeToString(make([]byte, 32))
}

func TestConfigDatabaseDriver(t *testing.T) {
	key := validKey()

	t.Run("defaults to sqlite when DATABASE_URL is unset", func(t *testing.T) {
		t.Setenv("APP_ENCRYPTION_KEY", key)
		t.Setenv("SESSION_SECRET", key)
		t.Setenv("DATABASE_URL", "")
		t.Setenv("SQLITE_PATH", "")
		t.Setenv("DATABASE_DRIVER", "")

		cfg, err := Load()
		if err != nil {
			t.Fatalf("Load() error: %v", err)
		}
		if cfg.DatabaseDriver != DriverSQLite {
			t.Errorf("expected DriverSQLite, got %v", cfg.DatabaseDriver)
		}
		if cfg.DatabaseURL != "dockdeploy.db" {
			t.Errorf("expected dockdeploy.db, got %v", cfg.DatabaseURL)
		}
	})

	t.Run("uses SQLITE_PATH when DATABASE_URL is unset", func(t *testing.T) {
		t.Setenv("APP_ENCRYPTION_KEY", key)
		t.Setenv("SESSION_SECRET", key)
		t.Setenv("DATABASE_URL", "")
		t.Setenv("SQLITE_PATH", "/var/lib/dockdeploy/custom.db")
		t.Setenv("DATABASE_DRIVER", "")

		cfg, err := Load()
		if err != nil {
			t.Fatalf("Load() error: %v", err)
		}
		if cfg.DatabaseDriver != DriverSQLite {
			t.Errorf("expected DriverSQLite, got %v", cfg.DatabaseDriver)
		}
		if cfg.DatabaseURL != "/var/lib/dockdeploy/custom.db" {
			t.Errorf("expected /var/lib/dockdeploy/custom.db, got %v", cfg.DatabaseURL)
		}
	})

	t.Run("detects postgres from DATABASE_URL prefix", func(t *testing.T) {
		t.Setenv("APP_ENCRYPTION_KEY", key)
		t.Setenv("SESSION_SECRET", key)
		t.Setenv("DATABASE_URL", "postgres://user:pass@localhost:5432/dockdeploy")
		t.Setenv("DATABASE_DRIVER", "")

		cfg, err := Load()
		if err != nil {
			t.Fatalf("Load() error: %v", err)
		}
		if cfg.DatabaseDriver != DriverPostgres {
			t.Errorf("expected DriverPostgres, got %v", cfg.DatabaseDriver)
		}
		if cfg.DatabaseURL != "postgres://user:pass@localhost:5432/dockdeploy" {
			t.Errorf("unexpected database URL: %v", cfg.DatabaseURL)
		}
	})

	t.Run("detects sqlite from sqlite: prefix", func(t *testing.T) {
		t.Setenv("APP_ENCRYPTION_KEY", key)
		t.Setenv("SESSION_SECRET", key)
		t.Setenv("DATABASE_URL", "sqlite:///tmp/test.db")
		t.Setenv("DATABASE_DRIVER", "")

		cfg, err := Load()
		if err != nil {
			t.Fatalf("Load() error: %v", err)
		}
		if cfg.DatabaseDriver != DriverSQLite {
			t.Errorf("expected DriverSQLite, got %v", cfg.DatabaseDriver)
		}
		if cfg.DatabaseURL != "/tmp/test.db" {
			t.Errorf("expected /tmp/test.db, got %v", cfg.DatabaseURL)
		}
	})

	t.Run("defaults port to 8081 and app url to http://localhost:8081", func(t *testing.T) {
		t.Setenv("APP_ENCRYPTION_KEY", key)
		t.Setenv("SESSION_SECRET", key)
		t.Setenv("PORT", "")
		t.Setenv("APP_URL", "")

		cfg, err := Load()
		if err != nil {
			t.Fatalf("Load() error: %v", err)
		}
		if cfg.Port != 8081 {
			t.Errorf("expected Port 8081, got %d", cfg.Port)
		}
		if cfg.AppURL != "http://localhost:8081" {
			t.Errorf("expected AppURL http://localhost:8081, got %s", cfg.AppURL)
		}
	})

	t.Run("auto-generates and reloads persistent secrets when unset in local mode", func(t *testing.T) {
		tmpDir := t.TempDir()
		secretsFile := tmpDir + "/test.key"

		t.Setenv("APP_ENCRYPTION_KEY", "")
		t.Setenv("SESSION_SECRET", "")
		t.Setenv("DATABASE_URL", "")
		t.Setenv("SQLITE_PATH", tmpDir+"/test.db")
		t.Setenv("SECRETS_FILE", secretsFile)

		cfg1, err := Load()
		if err != nil {
			t.Fatalf("first Load() failed: %v", err)
		}
		if !cfg1.AutoGeneratedSecrets {
			t.Errorf("expected AutoGeneratedSecrets to be true")
		}
		if len(cfg1.EncryptionKey) != EncryptionKeySize {
			t.Errorf("expected 32 byte encryption key, got %d", len(cfg1.EncryptionKey))
		}
		if len(cfg1.SessionSecret) < 32 {
			t.Errorf("expected session secret >= 32 bytes, got %d", len(cfg1.SessionSecret))
		}

		// Second call should reload the exact same keys
		cfg2, err := Load()
		if err != nil {
			t.Fatalf("second Load() failed: %v", err)
		}
		if string(cfg1.EncryptionKey) != string(cfg2.EncryptionKey) {
			t.Errorf("expected reloaded encryption key to match original")
		}
		if string(cfg1.SessionSecret) != string(cfg2.SessionSecret) {
			t.Errorf("expected reloaded session secret to match original")
		}
	})
}
