package ai

import (
	"fmt"
	"strings"
)

// NginxConfigSpec describes the requirements for generating an Nginx configuration.
type NginxConfigSpec struct {
	Domain            string `json:"domain"`
	UpstreamPort      int    `json:"upstream_port"`
	UpstreamHost      string `json:"upstream_host"` // defaults to 127.0.0.1
	EnableSSL         bool   `json:"enable_ssl"`
	CertPath          string `json:"cert_path"`
	KeyPath           string `json:"key_path"`
	EnableWebSocket   bool   `json:"enable_websocket"`
	ClientMaxBodySize string `json:"client_max_body_size"` // e.g. "50M"
	IncludeSecurity   bool   `json:"include_security"`
}

// GenerateSafeNginxConfig generates an Nginx virtual host configuration strictly adhering to dockdeploy's architecture.
func GenerateSafeNginxConfig(spec NginxConfigSpec) string {
	if spec.UpstreamHost == "" {
		spec.UpstreamHost = "127.0.0.1"
	}
	if spec.ClientMaxBodySize == "" {
		spec.ClientMaxBodySize = "50M"
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# Nginx configuration for %s (Generated by dockdeploy AI Assistant)\n\n", spec.Domain))

	if spec.EnableSSL {
		// HTTP -> HTTPS redirect block + ACME challenge
		sb.WriteString("server {\n")
		sb.WriteString("    listen 80;\n")
		sb.WriteString("    listen [::]:80;\n")
		sb.WriteString(fmt.Sprintf("    server_name %s;\n\n", spec.Domain))
		sb.WriteString("    # ACME challenge location for Let's Encrypt certbot webroot\n")
		sb.WriteString("    location /.well-known/acme-challenge/ {\n")
		sb.WriteString("        root /var/www/certbot;\n")
		sb.WriteString("        try_files $uri =404;\n")
		sb.WriteString("    }\n\n")
		sb.WriteString("    location / {\n")
		sb.WriteString("        return 301 https://$host$request_uri;\n")
		sb.WriteString("    }\n")
		sb.WriteString("}\n\n")

		// HTTPS Server block
		sb.WriteString("server {\n")
		sb.WriteString("    listen 443 ssl http2;\n")
		sb.WriteString("    listen [::]:443 ssl http2;\n")
		sb.WriteString(fmt.Sprintf("    server_name %s;\n\n", spec.Domain))

		certPath := spec.CertPath
		if certPath == "" {
			certPath = fmt.Sprintf("/etc/letsencrypt/live/%s/fullchain.pem", spec.Domain)
		}
		keyPath := spec.KeyPath
		if keyPath == "" {
			keyPath = fmt.Sprintf("/etc/letsencrypt/live/%s/privkey.pem", spec.Domain)
		}
		sb.WriteString(fmt.Sprintf("    ssl_certificate %s;\n", certPath))
		sb.WriteString(fmt.Sprintf("    ssl_certificate_key %s;\n", keyPath))
		sb.WriteString("    ssl_protocols TLSv1.2 TLSv1.3;\n")
		sb.WriteString("    ssl_prefer_server_ciphers on;\n")
		sb.WriteString("    ssl_ciphers HIGH:!aNULL:!MD5;\n\n")
	} else {
		// HTTP Server block
		sb.WriteString("server {\n")
		sb.WriteString("    listen 80;\n")
		sb.WriteString("    listen [::]:80;\n")
		sb.WriteString(fmt.Sprintf("    server_name %s;\n\n", spec.Domain))
		sb.WriteString("    # ACME challenge for future Let's Encrypt issuance\n")
		sb.WriteString("    location /.well-known/acme-challenge/ {\n")
		sb.WriteString("        root /var/www/certbot;\n")
		sb.WriteString("        try_files $uri =404;\n")
		sb.WriteString("    }\n\n")
	}

	sb.WriteString(fmt.Sprintf("    client_max_body_size %s;\n\n", spec.ClientMaxBodySize))

	if spec.IncludeSecurity {
		sb.WriteString("    # Security Headers\n")
		sb.WriteString("    add_header X-Content-Type-Options nosniff always;\n")
		sb.WriteString("    add_header X-XSS-Protection \"1; mode=block\" always;\n")
		sb.WriteString("    add_header Referrer-Policy strict-origin-when-cross-origin always;\n\n")
	}

	sb.WriteString("    location / {\n")
	sb.WriteString(fmt.Sprintf("        proxy_pass http://%s:%d;\n", spec.UpstreamHost, spec.UpstreamPort))
	sb.WriteString("        proxy_set_header Host $host;\n")
	sb.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
	sb.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
	sb.WriteString("        proxy_set_header X-Forwarded-Proto $scheme;\n")
	sb.WriteString("        proxy_set_header X-Forwarded-Host $host;\n")
	sb.WriteString("        proxy_set_header X-Forwarded-Port $server_port;\n\n")

	if spec.EnableWebSocket {
		sb.WriteString("        # WebSocket proxy support\n")
		sb.WriteString("        proxy_http_version 1.1;\n")
		sb.WriteString("        proxy_set_header Upgrade $http_upgrade;\n")
		sb.WriteString("        proxy_set_header Connection \"upgrade\";\n\n")
	}

	sb.WriteString("        proxy_read_timeout 300s;\n")
	sb.WriteString("        proxy_connect_timeout 60s;\n")
	sb.WriteString("        proxy_send_timeout 300s;\n")
	sb.WriteString("    }\n")
	sb.WriteString("}\n")

	return sb.String()
}
